use_frameworks!

platform :ios, '9.0'

target 'TileKit_Example' do
  pod 'TileKit', :path => '../'
#  pod 'ComponentKit', '~> 0.30'
#  pod 'Yoga'
  pod 'RenderCore', :path => '../'
#  pod 'RenderCore'
  pod 'ComponentKit', :path => '../'
  pod 'ComponentTextKit', :path => '../'

  target 'TileKit_Tests' do
    inherit! :search_paths
  end
end
